export let movies = [
  {
    id: 1,
    title: "3 Idiots",
    genre: "comedy",
    language: "hindi",
    rating: 4.8,
    releaseYear: 2009,
    duration: 170,
    availableOnOTT: true,
  },
  {
    id: 2,
    title: "Dangal",
    genre: "sports",
    language: "hindi",
    rating: 4.7,
    releaseYear: 2016,
    duration: 161,
    availableOnOTT: true,
  },
  {
    id: 3,
    title: "Lagaan",
    genre: "sports",
    language: "hindi",
    rating: 4.6,
    releaseYear: 2001,
    duration: 224,
    availableOnOTT: true,
  },
  {
    id: 4,
    title: "Sholay",
    genre: "action",
    language: "hindi",
    rating: 4.8,
    releaseYear: 1975,
    duration: 204,
    availableOnOTT: true,
  },
  {
    id: 5,
    title: "Gully Boy",
    genre: "drama",
    language: "hindi",
    rating: 4.2,
    releaseYear: 2019,
    duration: 153,
    availableOnOTT: true,
  },
  {
    id: 6,
    title: "Queen",
    genre: "drama",
    language: "hindi",
    rating: 4.4,
    releaseYear: 2013,
    duration: 146,
    availableOnOTT: true,
  },
  {
    id: 7,
    title: "Andhadhun",
    genre: "thriller",
    language: "hindi",
    rating: 4.5,
    releaseYear: 2018,
    duration: 139,
    availableOnOTT: true,
  },
  {
    id: 8,
    title: "Drishyam",
    genre: "thriller",
    language: "hindi",
    rating: 4.4,
    releaseYear: 2015,
    duration: 163,
    availableOnOTT: true,
  },
  {
    id: 9,
    title: "Drishyam 2",
    genre: "thriller",
    language: "hindi",
    rating: 4.3,
    releaseYear: 2022,
    duration: 140,
    availableOnOTT: true,
  },
  {
    id: 10,
    title: "Swades",
    genre: "drama",
    language: "hindi",
    rating: 4.6,
    releaseYear: 2004,
    duration: 189,
    availableOnOTT: true,
  },
  {
    id: 11,
    title: "Chak De India",
    genre: "sports",
    language: "hindi",
    rating: 4.5,
    releaseYear: 2007,
    duration: 153,
    availableOnOTT: true,
  },
  {
    id: 12,
    title: "Taare Zameen Par",
    genre: "drama",
    language: "hindi",
    rating: 4.7,
    releaseYear: 2007,
    duration: 165,
    availableOnOTT: true,
  },
  {
    id: 13,
    title: "PK",
    genre: "comedy",
    language: "hindi",
    rating: 4.3,
    releaseYear: 2014,
    duration: 153,
    availableOnOTT: true,
  },
  {
    id: 14,
    title: "Barfi",
    genre: "romance",
    language: "hindi",
    rating: 4.2,
    releaseYear: 2012,
    duration: 151,
    availableOnOTT: true,
  },
  {
    id: 15,
    title: "Zindagi Na Milegi Dobara",
    genre: "drama",
    language: "hindi",
    rating: 4.4,
    releaseYear: 2011,
    duration: 155,
    availableOnOTT: true,
  },
  {
    id: 16,
    title: "Dil Chahta Hai",
    genre: "drama",
    language: "hindi",
    rating: 4.3,
    releaseYear: 2001,
    duration: 183,
    availableOnOTT: true,
  },
  {
    id: 17,
    title: "Rockstar",
    genre: "romance",
    language: "hindi",
    rating: 4.1,
    releaseYear: 2011,
    duration: 159,
    availableOnOTT: true,
  },
  {
    id: 18,
    title: "Kabir Singh",
    genre: "romance",
    language: "hindi",
    rating: 3.8,
    releaseYear: 2019,
    duration: 172,
    availableOnOTT: true,
  },
  {
    id: 19,
    title: "War",
    genre: "action",
    language: "hindi",
    rating: 4.0,
    releaseYear: 2019,
    duration: 154,
    availableOnOTT: true,
  },
  {
    id: 20,
    title: "Pathaan",
    genre: "action",
    language: "hindi",
    rating: 4.0,
    releaseYear: 2023,
    duration: 146,
    availableOnOTT: true,
  },
  {
    id: 21,
    title: "Jawan",
    genre: "action",
    language: "hindi",
    rating: 4.2,
    releaseYear: 2023,
    duration: 169,
    availableOnOTT: true,
  },
  {
    id: 22,
    title: "Animal",
    genre: "action",
    language: "hindi",
    rating: 3.9,
    releaseYear: 2023,
    duration: 201,
    availableOnOTT: true,
  },
  {
    id: 23,
    title: "Stree",
    genre: "horror-comedy",
    language: "hindi",
    rating: 4.1,
    releaseYear: 2018,
    duration: 128,
    availableOnOTT: true,
  },
  {
    id: 24,
    title: "Bhediya",
    genre: "horror-comedy",
    language: "hindi",
    rating: 3.8,
    releaseYear: 2022,
    duration: 156,
    availableOnOTT: true,
  },
  {
    id: 25,
    title: "Kantara",
    genre: "thriller",
    language: "kannada",
    rating: 4.5,
    releaseYear: 2022,
    duration: 148,
    availableOnOTT: true,
  },
  {
    id: 26,
    title: "KGF Chapter 1",
    genre: "action",
    language: "kannada",
    rating: 4.3,
    releaseYear: 2018,
    duration: 156,
    availableOnOTT: true,
  },
  {
    id: 27,
    title: "KGF Chapter 2",
    genre: "action",
    language: "kannada",
    rating: 4.4,
    releaseYear: 2022,
    duration: 168,
    availableOnOTT: true,
  },
  {
    id: 28,
    title: "RRR",
    genre: "action",
    language: "telugu",
    rating: 4.6,
    releaseYear: 2022,
    duration: 187,
    availableOnOTT: true,
  },
  {
    id: 29,
    title: "Baahubali The Beginning",
    genre: "action",
    language: "telugu",
    rating: 4.5,
    releaseYear: 2015,
    duration: 159,
    availableOnOTT: true,
  },
  {
    id: 30,
    title: "Baahubali The Conclusion",
    genre: "action",
    language: "telugu",
    rating: 4.7,
    releaseYear: 2017,
    duration: 167,
    availableOnOTT: true,
  },
  {
    id: 31,
    title: "Pushpa",
    genre: "action",
    language: "telugu",
    rating: 4.1,
    releaseYear: 2021,
    duration: 179,
    availableOnOTT: true,
  },
  {
    id: 32,
    title: "Arjun Reddy",
    genre: "romance",
    language: "telugu",
    rating: 4.0,
    releaseYear: 2017,
    duration: 182,
    availableOnOTT: true,
  },
  {
    id: 33,
    title: "Vikram",
    genre: "action",
    language: "tamil",
    rating: 4.5,
    releaseYear: 2022,
    duration: 174,
    availableOnOTT: true,
  },
  {
    id: 34,
    title: "Master",
    genre: "action",
    language: "tamil",
    rating: 4.0,
    releaseYear: 2021,
    duration: 179,
    availableOnOTT: true,
  },
  {
    id: 35,
    title: "Super Deluxe",
    genre: "drama",
    language: "tamil",
    rating: 4.4,
    releaseYear: 2019,
    duration: 176,
    availableOnOTT: true,
  },
  {
    id: 36,
    title: "Jai Bhim",
    genre: "drama",
    language: "tamil",
    rating: 4.8,
    releaseYear: 2021,
    duration: 164,
    availableOnOTT: true,
  },
  {
    id: 37,
    title: "Asuran",
    genre: "action",
    language: "tamil",
    rating: 4.6,
    releaseYear: 2019,
    duration: 141,
    availableOnOTT: true,
  },
  {
    id: 38,
    title: "Premam",
    genre: "romance",
    language: "malayalam",
    rating: 4.4,
    releaseYear: 2015,
    duration: 156,
    availableOnOTT: true,
  },
  {
    id: 39,
    title: "Kumbalangi Nights",
    genre: "drama",
    language: "malayalam",
    rating: 4.6,
    releaseYear: 2019,
    duration: 135,
    availableOnOTT: true,
  },
  {
    id: 40,
    title: "Drishyam Malayalam",
    genre: "thriller",
    language: "malayalam",
    rating: 4.7,
    releaseYear: 2013,
    duration: 160,
    availableOnOTT: true,
  },
  {
    id: 41,
    title: "The Dark Knight",
    genre: "action",
    language: "english",
    rating: 4.9,
    releaseYear: 2008,
    duration: 152,
    availableOnOTT: true,
  },
  {
    id: 42,
    title: "Inception",
    genre: "sci-fi",
    language: "english",
    rating: 4.8,
    releaseYear: 2010,
    duration: 148,
    availableOnOTT: true,
  },
  {
    id: 43,
    title: "Interstellar",
    genre: "sci-fi",
    language: "english",
    rating: 4.9,
    releaseYear: 2014,
    duration: 169,
    availableOnOTT: true,
  },
  {
    id: 44,
    title: "Avatar",
    genre: "sci-fi",
    language: "english",
    rating: 4.5,
    releaseYear: 2009,
    duration: 162,
    availableOnOTT: true,
  },
  {
    id: 45,
    title: "Titanic",
    genre: "romance",
    language: "english",
    rating: 4.6,
    releaseYear: 1997,
    duration: 195,
    availableOnOTT: true,
  },
  {
    id: 46,
    title: "The Matrix",
    genre: "sci-fi",
    language: "english",
    rating: 4.7,
    releaseYear: 1999,
    duration: 136,
    availableOnOTT: true,
  },
  {
    id: 47,
    title: "John Wick",
    genre: "action",
    language: "english",
    rating: 4.3,
    releaseYear: 2014,
    duration: 101,
    availableOnOTT: true,
  },
  {
    id: 48,
    title: "The Hangover",
    genre: "comedy",
    language: "english",
    rating: 4.1,
    releaseYear: 2009,
    duration: 100,
    availableOnOTT: true,
  },
  {
    id: 49,
    title: "Parasite",
    genre: "thriller",
    language: "korean",
    rating: 4.8,
    releaseYear: 2019,
    duration: 132,
    availableOnOTT: true,
  },
  {
    id: 50,
    title: "Train to Busan",
    genre: "thriller",
    language: "korean",
    rating: 4.5,
    releaseYear: 2016,
    duration: 118,
    availableOnOTT: false,
  },
];
